steps:
 name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cohesive-feat-403611/reactgkeapp:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cohesive-feat-403611/reactgkeapp:$SHORT_SHA', '.']
