steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cohesive-feat-403611/github.com/wowmind/cloudrun-build:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cohesive-feat-403611/github.com/wowmind/cloudrun-build:$SHORT_SHA']
